### ISSUE TITLE
Site navigation missing

### ISSUE THREAD

**Issue by ascott1** [cfpb/cfgov-sheer-templates#18]
I posted about this in an Owning a Home pull request, but wanted to log an issue. The site-wide navigation for Sheer sites appears to be missing.

![screen shot 2016-05-24 at 6 54 46 am](https://cloud.githubusercontent.com/assets/212533/15501780/530bc10e-217d-11e6-827e-597c62158150.png)

**Comment by Scotchester** [comment]
Fixed!
